### ISSUE TITLE
License / Attributions?

### ISSUE THREAD

**Issue by fire-eggs** [adam-zheleznyak/colorful-life#1]
I've used your code for my project here:
https://github.com/fire-eggs/Adafruit-RGB-matrix-projects/tree/master/colorful-life

Anything I need to say about the license for your project? Do you have any requests for acknowledgements / attribution?

My thanks for your project!
Kevin

**Comment by adam-zheleznyak** [comment]
Your project looks great!

Just include my name and the project's url in the source code (which it looks like you already did).
